In [35]:
import torch

1. Создайте случайный FloatTensor размера 3x4x5

In [36]:
float_tensor = torch.randn(3, 4, 5).float()
float_tensor

tensor([[[-1.5606, -0.5049,  0.6200, -0.5995, -0.5417],
         [ 0.4957,  0.0108, -0.0875,  0.1748, -0.4492],
         [-0.4592,  0.4547,  1.3015,  0.3985, -1.1603],
         [-0.5737, -0.8639, -1.4462,  0.6224,  0.9626]],

        [[-0.8601, -0.1488,  0.1389,  1.3602,  1.5311],
         [-1.9783,  0.2973,  0.9620,  1.0573, -1.3132],
         [-0.5653, -1.6451, -0.3727,  1.2291,  1.3904],
         [-1.0392, -1.2950, -0.6406,  0.3588, -0.6097]],

        [[ 1.4098, -1.0929, -2.2166,  0.3010, -1.2913],
         [ 0.7134,  0.2307,  0.0887,  0.5035,  2.3086],
         [ 0.5699,  0.3753, -0.5845, -1.5437,  1.2786],
         [ 0.7093, -0.4611,  0.8300,  0.4885,  0.4068]]])

2. Выведите его форму (shape)

In [37]:
float_tensor.shape

torch.Size([3, 4, 5])

3. Приведите его к форме 6х10

In [38]:
float_tensor = float_tensor.reshape(6, 10)
float_tensor.size()

torch.Size([6, 10])

4. Создайте случайный IntTensor размера 10

In [39]:
int_tensor = torch.randn(10).int()
int_tensor

tensor([ 0,  0,  0,  0,  1,  1,  0,  0,  1, -1], dtype=torch.int32)

5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно

In [40]:
float_tensor * int_tensor

tensor([[-0.0000, -0.0000,  0.0000, -0.0000, -0.5417,  0.4957,  0.0000, -0.0000,
          0.1748,  0.4492],
        [-0.0000,  0.0000,  0.0000,  0.0000, -1.1603, -0.5737, -0.0000, -0.0000,
          0.6224, -0.9626],
        [-0.0000, -0.0000,  0.0000,  0.0000,  1.5311, -1.9783,  0.0000,  0.0000,
          1.0573,  1.3132],
        [-0.0000, -0.0000, -0.0000,  0.0000,  1.3904, -1.0392, -0.0000, -0.0000,
          0.3588,  0.6097],
        [ 0.0000, -0.0000, -0.0000,  0.0000, -1.2913,  0.7134,  0.0000,  0.0000,
          0.5035, -2.3086],
        [ 0.0000,  0.0000, -0.0000, -0.0000,  1.2786,  0.7093, -0.0000,  0.0000,
          0.4885, -0.4068]])

6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6

In [41]:
mm_tensor = float_tensor.mm(float_tensor.T)
mm_tensor.shape

torch.Size([6, 6])

7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

In [42]:
x = torch.tensor([1.0], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.0], requires_grad=True)

y = (x**3) + z - 75 * t
y.backward()
x.grad, z.grad, t.grad

(tensor([3.]), tensor([1.]), tensor([-75.]))

8. Создайте единичный тензор размера 5x6

In [43]:
nm_tensor = torch.randn(5, 6)

9. Переведите его в формат numpy

In [44]:
nm_tensor.numpy()

array([[-0.27715704, -1.2156173 ,  1.4350245 ,  0.59014773,  0.2618481 ,
         0.7262905 ],
       [-0.46999007,  0.16676185,  1.3453358 ,  1.4653674 ,  0.067793  ,
        -0.6525212 ],
       [-0.38039345, -1.586077  ,  0.02974742, -0.45338622,  0.3431252 ,
         1.6733127 ],
       [-1.0617934 ,  1.2676495 , -1.0438993 ,  1.4749331 ,  0.66691023,
         1.1344045 ],
       [ 0.31728905,  1.0538183 ,  0.07031902, -0.21018213, -0.32015094,
         2.7914813 ]], dtype=float32)